parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
  trigger: none

jobs:
- job: build
  displayName: Migration Job
  pool: 
    vmImage: ${{ parameters.image }}

  steps:
  - script: git clone https://gitlab-ci-token:2kFsjbjrYNW6Jrdzdrsw@gitlab.com/Kunwar55/gitlab-node.git
    displayName: Checkout code from Gitlab

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
